### PR TITLE
propose_docs_example

### PR DESCRIPTION
**Pull request by rafaqz**
# Description

Having runnable examples for all rules would probably help new users a lot. It might require some thought to make it an interesting enough example that they learn something from it. e.g. `AlleeExtinction` is pretty boring on its own.

This PR updates the docs guidelines to enforce adding examples from now on. Which will also require updating all the existing rules.

### CODE REVIEW

**Comment by virgile-baudrot** [comment]
Yes. @jamesmaino asked me what would be the thing to do for field ecologist using R to come in Julia. I think a zoo of examples you can copy/paste and makes it working would be great

**Comment by rafaqz** [comment]
Can you approve it then? ;)

**Comment by virgile-baudrot** [comment]
of course

**Comment by rafaqz** [comment]
I mean click "approve" in the review :). Its actually locked until its approved by someone

**Review by virgile-baudrot — APPROVED** [review]

**Pull request merged**
